services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: ra
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - custom-network

volumes:
  postgres-data:
    driver: local

networks:
  custom-network:
    driver: bridge