server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/ra
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

jwt:
  secret: ${JWT_SECRET:R1BYcTVXVGNDU2JmWHVnZ1lnN0FKeGR3cU1RUU45QXV4SDJONFZ3ckhwS1N0ZjNCYVkzZ0F4RVBSS1UzRENwRw==}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-token:
    expiration: 604800000 # 7 days

app:
  jwt:
    cookie:
      name: access_token
      refresh-name: refresh_token
      max-age: 86400         # 24 hours in seconds
      secure: true           # Only sent over HTTPS
      http-only: true        # Not accessible via JavaScript
      domain:                # Your domain (optional)
      path: /                # Path where cookie is valid
      same-site: Strict      # CSRF protection

# Google Drive API Configuration
google:
  service-account:
    key-file: classpath:service-account-key.json


