### Регистрация пользователя
POST http://localhost:8083/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123",
  "role": "USER"
}

### Аутентификация
POST http://localhost:8083/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Обновление токена
POST http://localhost:8083/api/v1/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NDM2NDgzMSwiZXhwIjoxNzQ0OTY5NjMxfQ.E1oh2spdSHZ3nQynsDWhRH0LZ0Us1Pvt0xX8bMikcKA


###
GET http://localhost:8083/api/v1/demo-controller
Cookie: access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NDk4MDAwNiwiZXhwIjoxNzQ0OTgxODA2fQ.bazih0UHnmaOpVRi86LEyU4IWKD9k36J2aYcF7V6QKU; refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NDk4MDAwNiwiZXhwIjoxNzQ1NTg0ODA2fQ.jlPsI9ztQx31epYZwzG-q2z0_yQNM95nXWAxEbLTxwI
